/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as AppOnboardingRouteImport } from "./routes/_app.onboarding";
import { Route as AppRRestaurantIdRouteImport } from "./routes/_app.r.$restaurantId";
import { Route as AppRRestaurantIdIndexRouteImport } from "./routes/_app.r.$restaurantId.index";
import { Route as AppRRestaurantIdSettingsRouteImport } from "./routes/_app.r.$restaurantId.settings";
import { Route as AppRRestaurantIdTodayRouteImport } from "./routes/_app.r.$restaurantId.today";
import { Route as AppRRestaurantIdCustomersIndexRouteImport } from "./routes/_app.r.$restaurantId.customers.index";
import { Route as AppRRestaurantIdCustomersCustomerIdRouteImport } from "./routes/_app.r.$restaurantId.customers.$customerId";
import { Route as AppRRestaurantIdSettingsIndexRouteImport } from "./routes/_app.r.$restaurantId.settings.index";
import { Route as AppRRestaurantIdSettingsNotificationsRouteImport } from "./routes/_app.r.$restaurantId.settings.notifications";
import { Route as AppRRestaurantIdSettingsServicesRouteImport } from "./routes/_app.r.$restaurantId.settings.services";
import { Route as AppRRestaurantIdSettingsWidgetRouteImport } from "./routes/_app.r.$restaurantId.settings.widget";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => AppRoute,
} as any);
const AppRRestaurantIdRoute = AppRRestaurantIdRouteImport.update({
  id: "/r/$restaurantId",
  path: "/r/$restaurantId",
  getParentRoute: () => AppRoute,
} as any);
const AppRRestaurantIdIndexRoute = AppRRestaurantIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRRestaurantIdRoute,
} as any);
const AppRRestaurantIdSettingsRoute =
  AppRRestaurantIdSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AppRRestaurantIdRoute,
  } as any);
const AppRRestaurantIdTodayRoute = AppRRestaurantIdTodayRouteImport.update({
  id: "/today",
  path: "/today",
  getParentRoute: () => AppRRestaurantIdRoute,
} as any);
const AppRRestaurantIdCustomersIndexRoute =
  AppRRestaurantIdCustomersIndexRouteImport.update({
    id: "/customers/",
    path: "/customers/",
    getParentRoute: () => AppRRestaurantIdRoute,
  } as any);
const AppRRestaurantIdCustomersCustomerIdRoute =
  AppRRestaurantIdCustomersCustomerIdRouteImport.update({
    id: "/customers/$customerId",
    path: "/customers/$customerId",
    getParentRoute: () => AppRRestaurantIdRoute,
  } as any);
const AppRRestaurantIdSettingsIndexRoute =
  AppRRestaurantIdSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppRRestaurantIdSettingsRoute,
  } as any);
const AppRRestaurantIdSettingsNotificationsRoute =
  AppRRestaurantIdSettingsNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AppRRestaurantIdSettingsRoute,
  } as any);
const AppRRestaurantIdSettingsServicesRoute =
  AppRRestaurantIdSettingsServicesRouteImport.update({
    id: "/services",
    path: "/services",
    getParentRoute: () => AppRRestaurantIdSettingsRoute,
  } as any);
const AppRRestaurantIdSettingsWidgetRoute =
  AppRRestaurantIdSettingsWidgetRouteImport.update({
    id: "/widget",
    path: "/widget",
    getParentRoute: () => AppRRestaurantIdSettingsRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/onboarding": typeof AppOnboardingRoute;
  "/r/$restaurantId": typeof AppRRestaurantIdRouteWithChildren;
  "/r/$restaurantId/settings": typeof AppRRestaurantIdSettingsRouteWithChildren;
  "/r/$restaurantId/today": typeof AppRRestaurantIdTodayRoute;
  "/r/$restaurantId/": typeof AppRRestaurantIdIndexRoute;
  "/r/$restaurantId/customers/$customerId": typeof AppRRestaurantIdCustomersCustomerIdRoute;
  "/r/$restaurantId/settings/notifications": typeof AppRRestaurantIdSettingsNotificationsRoute;
  "/r/$restaurantId/settings/services": typeof AppRRestaurantIdSettingsServicesRoute;
  "/r/$restaurantId/settings/widget": typeof AppRRestaurantIdSettingsWidgetRoute;
  "/r/$restaurantId/customers/": typeof AppRRestaurantIdCustomersIndexRoute;
  "/r/$restaurantId/settings/": typeof AppRRestaurantIdSettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/onboarding": typeof AppOnboardingRoute;
  "/r/$restaurantId/today": typeof AppRRestaurantIdTodayRoute;
  "/r/$restaurantId": typeof AppRRestaurantIdIndexRoute;
  "/r/$restaurantId/customers/$customerId": typeof AppRRestaurantIdCustomersCustomerIdRoute;
  "/r/$restaurantId/settings/notifications": typeof AppRRestaurantIdSettingsNotificationsRoute;
  "/r/$restaurantId/settings/services": typeof AppRRestaurantIdSettingsServicesRoute;
  "/r/$restaurantId/settings/widget": typeof AppRRestaurantIdSettingsWidgetRoute;
  "/r/$restaurantId/customers": typeof AppRRestaurantIdCustomersIndexRoute;
  "/r/$restaurantId/settings": typeof AppRRestaurantIdSettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/_app/onboarding": typeof AppOnboardingRoute;
  "/_app/r/$restaurantId": typeof AppRRestaurantIdRouteWithChildren;
  "/_app/r/$restaurantId/settings": typeof AppRRestaurantIdSettingsRouteWithChildren;
  "/_app/r/$restaurantId/today": typeof AppRRestaurantIdTodayRoute;
  "/_app/r/$restaurantId/": typeof AppRRestaurantIdIndexRoute;
  "/_app/r/$restaurantId/customers/$customerId": typeof AppRRestaurantIdCustomersCustomerIdRoute;
  "/_app/r/$restaurantId/settings/notifications": typeof AppRRestaurantIdSettingsNotificationsRoute;
  "/_app/r/$restaurantId/settings/services": typeof AppRRestaurantIdSettingsServicesRoute;
  "/_app/r/$restaurantId/settings/widget": typeof AppRRestaurantIdSettingsWidgetRoute;
  "/_app/r/$restaurantId/customers/": typeof AppRRestaurantIdCustomersIndexRoute;
  "/_app/r/$restaurantId/settings/": typeof AppRRestaurantIdSettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/signup"
    | "/onboarding"
    | "/r/$restaurantId"
    | "/r/$restaurantId/settings"
    | "/r/$restaurantId/today"
    | "/r/$restaurantId/"
    | "/r/$restaurantId/customers/$customerId"
    | "/r/$restaurantId/settings/notifications"
    | "/r/$restaurantId/settings/services"
    | "/r/$restaurantId/settings/widget"
    | "/r/$restaurantId/customers/"
    | "/r/$restaurantId/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/onboarding"
    | "/r/$restaurantId/today"
    | "/r/$restaurantId"
    | "/r/$restaurantId/customers/$customerId"
    | "/r/$restaurantId/settings/notifications"
    | "/r/$restaurantId/settings/services"
    | "/r/$restaurantId/settings/widget"
    | "/r/$restaurantId/customers"
    | "/r/$restaurantId/settings";
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/login"
    | "/signup"
    | "/_app/onboarding"
    | "/_app/r/$restaurantId"
    | "/_app/r/$restaurantId/settings"
    | "/_app/r/$restaurantId/today"
    | "/_app/r/$restaurantId/"
    | "/_app/r/$restaurantId/customers/$customerId"
    | "/_app/r/$restaurantId/settings/notifications"
    | "/_app/r/$restaurantId/settings/services"
    | "/_app/r/$restaurantId/settings/widget"
    | "/_app/r/$restaurantId/customers/"
    | "/_app/r/$restaurantId/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/onboarding": {
      id: "/_app/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof AppOnboardingRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/r/$restaurantId": {
      id: "/_app/r/$restaurantId";
      path: "/r/$restaurantId";
      fullPath: "/r/$restaurantId";
      preLoaderRoute: typeof AppRRestaurantIdRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/r/$restaurantId/": {
      id: "/_app/r/$restaurantId/";
      path: "/";
      fullPath: "/r/$restaurantId/";
      preLoaderRoute: typeof AppRRestaurantIdIndexRouteImport;
      parentRoute: typeof AppRRestaurantIdRoute;
    };
    "/_app/r/$restaurantId/settings": {
      id: "/_app/r/$restaurantId/settings";
      path: "/settings";
      fullPath: "/r/$restaurantId/settings";
      preLoaderRoute: typeof AppRRestaurantIdSettingsRouteImport;
      parentRoute: typeof AppRRestaurantIdRoute;
    };
    "/_app/r/$restaurantId/today": {
      id: "/_app/r/$restaurantId/today";
      path: "/today";
      fullPath: "/r/$restaurantId/today";
      preLoaderRoute: typeof AppRRestaurantIdTodayRouteImport;
      parentRoute: typeof AppRRestaurantIdRoute;
    };
    "/_app/r/$restaurantId/customers/": {
      id: "/_app/r/$restaurantId/customers/";
      path: "/customers";
      fullPath: "/r/$restaurantId/customers/";
      preLoaderRoute: typeof AppRRestaurantIdCustomersIndexRouteImport;
      parentRoute: typeof AppRRestaurantIdRoute;
    };
    "/_app/r/$restaurantId/customers/$customerId": {
      id: "/_app/r/$restaurantId/customers/$customerId";
      path: "/customers/$customerId";
      fullPath: "/r/$restaurantId/customers/$customerId";
      preLoaderRoute: typeof AppRRestaurantIdCustomersCustomerIdRouteImport;
      parentRoute: typeof AppRRestaurantIdRoute;
    };
    "/_app/r/$restaurantId/settings/": {
      id: "/_app/r/$restaurantId/settings/";
      path: "/";
      fullPath: "/r/$restaurantId/settings/";
      preLoaderRoute: typeof AppRRestaurantIdSettingsIndexRouteImport;
      parentRoute: typeof AppRRestaurantIdSettingsRoute;
    };
    "/_app/r/$restaurantId/settings/notifications": {
      id: "/_app/r/$restaurantId/settings/notifications";
      path: "/notifications";
      fullPath: "/r/$restaurantId/settings/notifications";
      preLoaderRoute: typeof AppRRestaurantIdSettingsNotificationsRouteImport;
      parentRoute: typeof AppRRestaurantIdSettingsRoute;
    };
    "/_app/r/$restaurantId/settings/services": {
      id: "/_app/r/$restaurantId/settings/services";
      path: "/services";
      fullPath: "/r/$restaurantId/settings/services";
      preLoaderRoute: typeof AppRRestaurantIdSettingsServicesRouteImport;
      parentRoute: typeof AppRRestaurantIdSettingsRoute;
    };
    "/_app/r/$restaurantId/settings/widget": {
      id: "/_app/r/$restaurantId/settings/widget";
      path: "/widget";
      fullPath: "/r/$restaurantId/settings/widget";
      preLoaderRoute: typeof AppRRestaurantIdSettingsWidgetRouteImport;
      parentRoute: typeof AppRRestaurantIdSettingsRoute;
    };
  }
}

interface AppRRestaurantIdSettingsRouteChildren {
  AppRRestaurantIdSettingsNotificationsRoute: typeof AppRRestaurantIdSettingsNotificationsRoute;
  AppRRestaurantIdSettingsServicesRoute: typeof AppRRestaurantIdSettingsServicesRoute;
  AppRRestaurantIdSettingsWidgetRoute: typeof AppRRestaurantIdSettingsWidgetRoute;
  AppRRestaurantIdSettingsIndexRoute: typeof AppRRestaurantIdSettingsIndexRoute;
}

const AppRRestaurantIdSettingsRouteChildren: AppRRestaurantIdSettingsRouteChildren =
  {
    AppRRestaurantIdSettingsNotificationsRoute:
      AppRRestaurantIdSettingsNotificationsRoute,
    AppRRestaurantIdSettingsServicesRoute:
      AppRRestaurantIdSettingsServicesRoute,
    AppRRestaurantIdSettingsWidgetRoute: AppRRestaurantIdSettingsWidgetRoute,
    AppRRestaurantIdSettingsIndexRoute: AppRRestaurantIdSettingsIndexRoute,
  };

const AppRRestaurantIdSettingsRouteWithChildren =
  AppRRestaurantIdSettingsRoute._addFileChildren(
    AppRRestaurantIdSettingsRouteChildren,
  );

interface AppRRestaurantIdRouteChildren {
  AppRRestaurantIdSettingsRoute: typeof AppRRestaurantIdSettingsRouteWithChildren;
  AppRRestaurantIdTodayRoute: typeof AppRRestaurantIdTodayRoute;
  AppRRestaurantIdIndexRoute: typeof AppRRestaurantIdIndexRoute;
  AppRRestaurantIdCustomersCustomerIdRoute: typeof AppRRestaurantIdCustomersCustomerIdRoute;
  AppRRestaurantIdCustomersIndexRoute: typeof AppRRestaurantIdCustomersIndexRoute;
}

const AppRRestaurantIdRouteChildren: AppRRestaurantIdRouteChildren = {
  AppRRestaurantIdSettingsRoute: AppRRestaurantIdSettingsRouteWithChildren,
  AppRRestaurantIdTodayRoute: AppRRestaurantIdTodayRoute,
  AppRRestaurantIdIndexRoute: AppRRestaurantIdIndexRoute,
  AppRRestaurantIdCustomersCustomerIdRoute:
    AppRRestaurantIdCustomersCustomerIdRoute,
  AppRRestaurantIdCustomersIndexRoute: AppRRestaurantIdCustomersIndexRoute,
};

const AppRRestaurantIdRouteWithChildren =
  AppRRestaurantIdRoute._addFileChildren(AppRRestaurantIdRouteChildren);

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute;
  AppRRestaurantIdRoute: typeof AppRRestaurantIdRouteWithChildren;
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppRRestaurantIdRoute: AppRRestaurantIdRouteWithChildren,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
